version: '3.8'

services:
  task_manage:
    image: postgres:latest
    container_name: task_manage
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: pgdb
    restart: always
