# Generated by Django 5.0.6 on 2024-06-28 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_label_updated_alter_label_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'ordering': ['-created'], 'verbose_name': 'Label', 'verbose_name_plural': 'Labels'},
        ),
    ]
