# Generated by Django 5.0.6 on 2024-06-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0003_alter_status_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='updated'),
        ),
    ]
