# Generated by Django 5.0.6 on 2024-06-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0004_status_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['-created'], 'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
