# Generated by Django 5.0.6 on 2024-06-07 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 7, 13, 22, 54, 353331, tzinfo=datetime.timezone.utc), verbose_name='created'),
        ),
    ]
